# Generated by Django 5.0.6 on 2024-07-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedSync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_profile_pic',
            field=models.TextField(blank=True),
        ),
    ]
