# Generated by Django 5.0.6 on 2024-07-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeedSync', '0002_posts_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user_profile_pic',
        ),
    ]
