# Generated by Django 5.0.6 on 2024-07-30 21:44

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedSync', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_picture',
            field=models.TextField(blank=True, null=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
