# Generated by Django 5.0.6 on 2024-08-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedSync', '0012_posts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.TextField(),
        ),
    ]
