# Generated by Django 5.0.6 on 2024-10-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeedSync', '0014_messages'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
