# Generated by Django 5.0.6 on 2024-10-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedSync', '0016_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.TextField(blank=True, default='https://scontent-lga3-1.xx.fbcdn.net/v/t1.30497-1/453178253_471506465671661_2781666950760530985_n.png?stp=dst-png_s200x200&_nc_cat=1&ccb=1-7&_nc_sid=136b72&_nc_ohc=5aCdrv5LSSkQ7kNvgGthpUo&_nc_ht=scontent-lga3-1.xx&_nc_gid=A8Zq6-UA-8X0iH3ISQ02m6W&oh=00_AYCHBsPTMlb6AlxvjKdlE1p4JgiKixsosSKdD7rWkREgMg&oe=6743927A', null=True),
        ),
    ]
