# Generated by Django 5.0.6 on 2024-10-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedSync', '0018_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
