# Generated by Django 5.0.6 on 2024-10-31 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FeedSync', '0019_alter_posts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cover_picture',
        ),
    ]
