# Generated by Django 5.0.6 on 2024-11-07 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedSync', '0021_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, related_name='sending_notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
