# Generated by Django 5.0.6 on 2024-11-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedSync', '0022_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
